# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-27 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_id', models.IntegerField(default=0)),
                ('building_type', models.TextField(default='', max_length=50)),
                ('building_mode', models.TextField(default='fill')),
                ('building_led_max', models.IntegerField(default=0)),
                ('building_led_min', models.IntegerField(default=0)),
                ('building_red', models.IntegerField(default=0)),
                ('building_green', models.IntegerField(default=0)),
                ('building_blue', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('motor_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('motor_on', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Oled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oled_id', models.IntegerField(default=0)),
                ('oled_on', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OledImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_image', models.ImageField(upload_to='')),
                ('image_thumbnail', models.ImageField(upload_to='')),
                ('image_oled', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StripControlApp.Oled')),
            ],
        ),
        migrations.CreateModel(
            name='StreetLight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_light_id', models.IntegerField(default=0)),
                ('street_light_on', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Strip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strip_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TrafficLight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traffic_id', models.IntegerField(default=0)),
                ('traffic_on', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='streetlight',
            name='street_light_strip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StripControlApp.Strip'),
        ),
        migrations.AddField(
            model_name='building',
            name='building_strip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StripControlApp.Strip'),
        ),
    ]
