# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-27 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StripControlApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trafficlight',
            old_name='traffic_id',
            new_name='traffic_light_id',
        ),
        migrations.RenameField(
            model_name='trafficlight',
            old_name='traffic_on',
            new_name='traffic_light_mode',
        ),
    ]
